export enum AutoIncrementEnum {
    USER = "U",
    ENTITY = "EN",
    COMPANY = "COM",
    STUDENT = "ST",
    COURSE = "COU",
    EMPLOYEE = "EM",
    ROLE = "RO",
    PERMISSION = "PE",
    SUBJECT = "SU",
    PROBLEMSTATEMENT = "PS",
    SOLUTION = "SOL",
    ANNOUNCEMENT = "AN",
    SUBSCRIPTION = "SUB",
    ENROLLMENT = "ENROL",
}
